# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-16 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User'), (2, 'Author'), (3, 'Admin')], null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Surname')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/series')),
                ('is_public', models.BooleanField(default=True, verbose_name='Show on site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
